Adding a SEP for change proposed changes to the pkg beacon.
saltstack/salt-enhancement-proposals pull request #39
Opened 2020-12-18 22:53 UTC by garethgreenaway

Adding a SEP for change proposed changes to the pkg beacon.

2020-12-18 23:43 UTC, Akm0d approved these changes

2022-01-05 23:15 UTC, waynew requested changes

2022-01-05 23:15 UTC, waynew commented on 0029-pkg-beacon-updates.md
> +Because of the way beacons work, this change will also require changes to all PKG modules to ensure that there is the option in the form of a keyword argument to pull an updated list of installed pac
**typo** `__context__` dunder.

2022-01-05 23:15 UTC, waynew commented on 0029-pkg-beacon-updates.md
> +This change would be an enhancement to the PKG beacon, brining additional functionality.
**typo** s/brining/bringing

2022-02-15 15:40 UTC, waynew commented
This SEP was approved and implemented

2022-02-15 15:40 UTC, merged